apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-metro-route
spec:
  selector:
    matchLabels:
      app: metro-route
  replicas: 3
  template:
    metadata:
      labels:
        app: metro-route
    spec:
      containers:
        - name: metro-route
          image: "localhost:5000/metro-route-service:1.1"
          env:
          # This container requires a derby database to be running
          - name: DERBY_DB_SERVER
            value: ${SERVICE_METRO_DERBY_SERVICE_HOST}
          - name: DERBY_DB_PORT
            value: ${SERVICE_METRO_DERBY_SERVICE_PORT}
          - name: DERBY_DB_USERNAME
            value: shibu
          - name: DERBY_DB_PASSWORD
            value: shibu
          ports:
            - name: route-http-port
              containerPort: 8101
